version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '05:17'
      timezone: UTC
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    versioning-strategy: increase
    commit-message:
      prefix: 'chore:dependencies:'
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '05:37'
      timezone: UTC
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'ci:github:'

  - package-ecosystem: docker
    directory: /deploy/production
    schedule:
      interval: weekly
      day: monday
      time: '05:57'
      timezone: UTC
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'build:docker:'
