declare const styles: {
  readonly accountAction: string;
  readonly accountCopy: string;
  readonly avatar: string;
  readonly brand: string;
  readonly brandMark: string;
  readonly environment: string;
  readonly healthDot: string;
  readonly main: string;
  readonly navIcon: string;
  readonly navigation: string;
  readonly navigationLink: string;
  readonly search: string;
  readonly shell: string;
  readonly skipLink: string;
  readonly toolbar: string;
  readonly topbar: string;
  readonly workspacePicker: string;
};
export default styles;
